# Generated by Django 5.1.1 on 2024-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guests', models.PositiveIntegerField(verbose_name='Number of Guests')),
                ('reservation_date', models.DateField(verbose_name='Reservation Date')),
                ('reservation_time', models.TimeField(verbose_name='Reservation Time')),
                ('seating_preference', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('bar', 'Bar'), ('booth', 'Booth')], max_length=20)),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
            ],
        ),
    ]
